config/routes.rb
require "monban/constraints/signed_in"

Rails.application.routes.draw do
  resources :users, only: [:none] do
    resources :password_resets, only: [:edit, :update]
  end
  resources :password_resets, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  constraints Monban::Constraints::SignedIn.new do
    get "/", to: "homes#show", as: :homes
    resources :users, only: [:show, :index] do
      resource :following_relationships, only: [:create, :destroy]
    end

    resources :shouts, only: [:show] do
      resource :spam, only: [:create]
    end

    resource :admin_options, only: [:show]
    resource :timeline, only: [:show]
    resources :text_shouts, only: [:create, :edit, :update, :destroy]
    resources :photo_shouts, only: [:create, :edit, :update, :destroy]
    resources :hashtags, only: [:show]
  end

  root to: "sessions#new", via: :get
end

app/models/shout.rb
class Shout < ActiveRecord::Base
  validates_associated :content
  validates :spam, inclusion: [true, false]

  belongs_to :user
  belongs_to :content, polymorphic: true

  default_scope { order(created_at: :desc) }

  def body=(new_body)
    self[:body] = new_body.upcase
  end

  def self.search(term)
    text_shouts = TextShout.where("body ILIKE ?", "%#{term}%")
    where(content_type: "TextShout", content_id: text_shouts)
  end

  def mark_as_spam
    update_attribute(:spam, true)
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  def show
    @shout = Shout.find(params[:id])
  end
end

app/helpers/shouts_helper.rb
require "digest/md5"

module ShoutsHelper
  def gravatar(user, size = 60)
    digest = Digest::MD5.hexdigest(user.email).downcase
    image_tag("http://gravatar.com/avatar/#{digest}?s=#{size}&r=pg&d=http://i36.photobucket.com/albums/e17/cordiallysherry/shout_gravatar_zps0d578c1f.png")
  end

  def shouterize(text)
    link_hashtags(strip_tags(text)).html_safe
  end

  private

  def link_hashtags(text)
    text.gsub(/#\w+/) { |match| link_to(match, hashtag_path(match[1..-1])) }
  end
end

app/views/shouts/_shout.html.erb
<%= div_for shout do %>
  <div class="row">
    <div class="col-md-1">
      <%= gravatar shout.user %>
    </div>
    <strong><%= link_to shout.user.username, shout.user %></strong>
    <%= link_to time_ago_in_words(shout.created_at), shout %>
    <p> <%= render shout.content %> </p>

    <% if current_user.owns?(shout) %>
      <%= link_to "Edit", edit_polymorphic_path(shout.content) %> |
      <%= link_to "Delete", shout.content, method: :delete %>
    <% elsif shout.spam? %>
      This shout has been reported and is under review
    <% else %>
      <%= link_to "Report", shout_spam_path(shout), method: :post %>
    <% end %>

    <% if current_user.try(:admin?) %>
      | <%= link_to "Remove", shout.content, method: :delete %>
    <% end %>
  </div>
<% end %>

app/views/shouts/show.html.erb
<%= render @shout %>